### ISSUE TITLE
Provide a state for "checking signIn status"

### ISSUE THREAD

**Issue by friedger** [njordhov/react-blockstack#4]
Currently, there is no way to decided whether a user is signed out/signed in or whether the app is still checking.

For better UX, there `useBlockstack` should return a `checkingUser` state.

**Comment by njordhov** [comment]
When authentication is pending, and only then, `signIn` and `signOut` are both null, so:

```javascript
const { signIn, signOut } = useBlockstack()
const checkingUser = (!signIn && !signOut)
```

See the [auth button example](https://github.com/njordhov/react-blockstack#example) for a use case.

**Comment by friedger** [comment]
This issue is for the state between starting the app and between finding out whether the user is signed in or not or pending

**Comment by njordhov** [comment]
Maybe something like:

```javascript 
const {signIn, signOut} = useBlockstack()
useElement ( () => {
  if (!signIn && !signOut) {
    document.documentElement.classList.add('blockstack-pending')
  } else {
    document.documentElement.classList.remove('blockstack-pending')
  }
},[signIn, signOut])
```

**Comment by njordhov** [comment]
For early detection of pending status, do like this in the `head` element:

```javascript
if ( location.search.startsWith("?authResponse=") {
  document.documentElement.classList.add('blockstack-pending');
}
```

**Comment by friedger** [comment]
No extra state needed as it can be checked as described above.
